apiVersion: v1
kind: Service
metadata:
  name: nginx-tools-proxy-svc
  namespace: cep-services-npdevops
  labels:
    app: nginx-tools-proxy
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: nginx-tools-proxy
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8080
status:
  loadBalancer: {}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-tools-proxy-config
  namespace: cep-services-npdevops
  labels:
    app: nginx-tools-proxy
data:
   nginx.conf: |
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
    worker_connections  1024;
    }
    http {
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile  on;
    keepalive_timeout 65;
    include /etc/nginx/conf.d/*.conf;
    upstream kibana {
      server kibana.cep-monitoring-nonprod.svc.cluster.local:80;
    }
        server {
        listen 8080 ssl;
        ssl_certificate /tmp/gcp.boots.com;
        ssl_certificate_key /tmp/gcp.boots.com.key;
        server_name gcpkibana.tools.boots.com;
        location /  {
        proxy_pass http://kibana;
        proxy_http_version 1.1;
       }

       }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tools-proxy-dep
  namespace: cep-services-npdevops
  labels:
    app: nginx-tools-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tools-proxy
  template:
    metadata:
      labels:
        app: nginx-tools-proxy
    spec:
      containers:
      - name: nginx
        image: gcpdevacr.azurecr.io/cep/nginx/nginx-1.15.8-bionic:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/nginx
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0644
          name: nginx-tools-proxy-config
      imagePullSecrets:
      - name: gcpdev01aksacr
